# Generated by Django 5.2.7 on 2025-11-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('original_content', models.TextField()),
                ('processed_content', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('medicine', 'Medicine'), ('fitness', 'Fitness'), ('nutrition', 'Nutrition'), ('lifestyle', 'Lifestyle')], max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
