# Generated by Django 5.2.7 on 2025-11-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
