# Generated by Django 5.2.7 on 2025-11-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL RSS-ленты', unique=True)),
                ('category', models.CharField(choices=[('medicine', 'Medicine'), ('fitness', 'Fitness'), ('nutrition', 'Nutrition'), ('lifestyle', 'Lifestyle')], help_text='Категория, в которую будут помещаться статьи из этой ленты', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли лента для опроса')),
                ('last_fetched', models.DateTimeField(blank=True, help_text='Время последнего опроса ленты', null=True)),
                ('fetch_frequency', models.IntegerField(default=30, help_text='Частота опроса ленты в минутах')),
            ],
            options={
                'verbose_name': 'RSS Feed',
                'verbose_name_plural': 'RSS Feeds',
            },
        ),
    ]
